name: CI for Pull Requests

# Trigger the workflow on pull requests targeting the `main` branch
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # # Step 3: Install dependencies
      # - name: Install dependencies
      #   run: |
      #     # python -m pip install --upgrade pip
      #     curl -sSf https://rye.astral.sh/get | bash

      #     # pip install -r requirements.txt
      #     rye sync

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-docker-image:latest .

      # TODO:
      # # Step 4: Run tests
      # - name: Run application tests
      #   run: |
      #     docker run --rm my-docker-image:latest pytest tests/
